export const GOALKEEPER_POWER_MULTIPLIER = 1.5;
export const DEFENDER_POWER_MULTIPLIER = 1.2;
export const MIDFIELDER_POWER_MULTIPLIER = 1.0;
export const ATTACKER_POWER_MULTIPLIER = 1.2;

export const GOALKEEPER_GOAL_MULTIPLIER = 0.0;
export const DEFENDER_GOAL_MULTIPLIER = 0.5;
export const MIDFIELDER_GOAL_MULTIPLIER = 1.0;
export const ATTACKER_GOAL_MULTIPLIER = 1.5;
export const STAR_GOAL_MULTIPLIER = 1.5;
export const BASE_GOAL_MULTIPLIER = 1.0;

export const ADJUSTED_ATTACK_ATTACK_MODIFIER = 1.0;
export const ADJUSTED_ATTACK_MIDFIELD_MODIFIER = 0.5;
export const ADJUSTED_DEFENSE_MIDFIELD_MODIFIER = 0.5;
export const ADJUSTED_DEFENSE_DEFENSE_MODIFIER = 1.0;

export const STAR_PLAYER_MULTIPLIER = 1.5;
export const BASE_PLAYER_MULTIPLIER = 1.0;

export const BASE_MORALE_EFFECT = 0.6;
export const MORALE_MULTIPLIER = 0.8;

// Must be greater than 10, which is the greater discipline
export const DISCIPLINE_THRESHOLD = 11.0;
export const RED_CARD_THRESHOLD = 0.0005;

export const BASE_TIME_FACTOR = 0.05;
export const MIN_DAYS_SUSPENSION = 1;
export const MAX_DAYS_SUSPENSION = 4;

export const COMBINED_FACTOR_MULTIPLIER_MOST_SEVERE = 0.1;
export const COMBINED_FACTOR_MULTIPLIER_SEVERE = 0.25;
export const COMBINED_FACTOR_MULTIPLIER_MODERATE = 0.6;

// Must sum 1.0
export const DISCIPLINE_INFLUENCE_FACTOR = 0.7;
export const TIME_INFLUENCE_FACTOR = 0.3;
