export const GOALKEEPER_POWER_MULTIPLIER = 1.5;
export const DEFENDER_POWER_MULTIPLIER = 1.2;
export const MIDFIELDER_POWER_MULTIPLIER = 1.0;
export const ATTACKER_POWER_MULTIPLIER = 1.2;

export const GOALKEEPER_GOAL_MULTIPLIER = 0.0;
export const DEFENDER_GOAL_MULTIPLIER = 0.5;
export const MIDFIELDER_GOAL_MULTIPLIER = 1.0;
export const ATTACKER_GOAL_MULTIPLIER = 1.5;
export const STAR_GOAL_MULTIPLIER = 1.5;
export const BASE_GOAL_MULTIPLIER = 1.0;

export const ADJUSTED_ATTACK_ATTACK_MODIFIER = 1.0;
export const ADJUSTED_ATTACK_MIDFIELD_MODIFIER = 0.5;
export const ADJUSTED_DEFENSE_MIDFIELD_MODIFIER = 0.5;
export const ADJUSTED_DEFENSE_DEFENSE_MODIFIER = 1.0;

export const STAR_PLAYER_MULTIPLIER = 1.5;
export const BASE_PLAYER_MULTIPLIER = 1.0;

export const BASE_MORALE_EFFECT = 0.6;
export const MORALE_MULTIPLIER = 0.8;

// Must be greater than 10, which is the greater discipline
export const DISCIPLINE_THRESHOLD = 11.0;
export const RED_CARD_THRESHOLD = 0.0005;
