export const MORALE_BOOST_WIN = 0.08;
export const MORALE_BOOST_DRAW = -0.03;
export const MORALE_BOOST_LOSS = -0.075;

export const MORALE_MIN = 0.1;
export const MORALE_MAX = 1.0;

export const INJURY_PRONENESS_TIME_FACTOR_MULTIPLIER = 1.6;
export const PREVIOUS_INJURIES_FACTOR_MULTIPLIER = 0.8;
export const INJURY_MAX_TIME = 10;
export const INJURY_TIME_MULTIPLIER = 0.0;

export const BASE_TIME_FACTOR = 0.05;
export const MIN_DAYS_SUSPENSION = 1;
export const MAX_DAYS_SUSPENSION = 4;
export const COMBINED_FACTOR_MULTIPLIER_MOST_SEVERE = 0.1;
export const COMBINED_FACTOR_MULTIPLIER_SEVERE = 0.25;
export const COMBINED_FACTOR_MULTIPLIER_MODERATE = 0.6;
// Must sum 1.0
export const DISCIPLINE_INFLUENCE_FACTOR = 0.7;
export const TIME_INFLUENCE_FACTOR = 0.3;

// PlayerPowerChange
export const INCREASE_DECREASE_POWER_TIME_THRESHOLD = 45;
export const INCREASE_UNDERUSED_PLAYER_POWER_PROBABILITY = 0.4;
export const QUADRATIC_FACTOR_POWER_INCREASE = 0.00005926;
export const LINEAR_FACTOR_POWER_INCREASE = 0.005333;
export const CONSTANT_FACTOR_POWER_INCREASE = 0.45;
export const QUADRATIC_FACTOR_POWER_DECREASE = 0.00005333;
export const LINEAR_FACTOR_POWER_DECREASE = 0.00493333;
export const CONSTANT_FACTOR_POWER_DECREASE = 0.33;
