import type { Color } from "../types";

export type TeamSeed = {
  name: string;
  fullname: string;
  base: number;
  foreground: Color;
  background: Color;
  border?: Color | "transparent";
  trainer: string;
};

export function brazilianTeams(): TeamSeed[] {
  return [
    {
      name: "Botafogo",
      fullname: "Botafogo de Futebol e Regatas",
      base: 18,
      foreground: "white",
      background: "black",
      trainer: "Artur Jorge",
    },
    {
      name: "Palmeiras",
      fullname: "Sociedade Esportiva Palmeiras",
      base: 18,
      foreground: "white",
      background: "green",
      border: "white",
      trainer: "Abel Ferreira",
    },
    {
      name: "Flamengo",
      fullname: "Clube de Regatas Flamengo",
      base: 18,
      foreground: "black",
      background: "red",
      trainer: "Filipe Luís",
    },
    {
      name: "Atlético-MG",
      fullname: "Clube Atlético Mineiro",
      base: 17,
      foreground: "white",
      background: "black",
      trainer: "Gabriel Milito",
    },
    {
      name: "São Paulo",
      fullname: "São Paulo Futebol Clube",
      base: 16,
      foreground: "red",
      background: "white",
      trainer: "Zubeldia",
    },
    {
      name: "Fortaleza",
      fullname: "Fortaleza Esporte Clube",
      base: 16,
      foreground: "blue",
      background: "red",
      trainer: "Vojvoda",
    },
    {
      name: "Internacional",
      fullname: "Sport Club Internacional",
      base: 16,
      foreground: "white",
      background: "red",
      trainer: "Roger Machado",
    },
    {
      name: "Grêmio",
      fullname: "Grêmio Football Porto Alegrense",
      base: 16,
      foreground: "white",
      background: "darkblue",
      trainer: "Renato Gaúcho",
    },
    {
      name: "Corinthians",
      fullname: "Sport Club Corinthians Paulista",
      base: 16,
      foreground: "black",
      background: "white",
      trainer: "Ramón Díaz",
    },
    {
      name: "Fluminense",
      fullname: "Fluminense Football Club",
      base: 15,
      foreground: "red",
      background: "green",
      border: "red",
      trainer: "Mano Menezes",
    },
    {
      name: "Cruzeiro",
      fullname: "Cruzeiro Esporte Clube",
      base: 15,
      foreground: "white",
      background: "darkblue",
      trainer: "Fernando Diniz",
    },
    {
      name: "Athlético",
      fullname: "Clube Atlhético Paranaense",
      base: 15,
      foreground: "red",
      background: "black",
      trainer: "Lucho González",
    },
    {
      name: "Bahia",
      fullname: "Esporte Clube Bahia",
      base: 15,
      foreground: "red",
      background: "darkblue",
      trainer: "Rogério Ceni",
    },
    {
      name: "Vasco",
      fullname: "Clube de Regatas Vasco da Gama",
      base: 15,
      foreground: "black",
      background: "white",
      trainer: "Rafael Paiva",
    },
    {
      name: "Bragantino",
      fullname: "Red Bull Bragantino",
      base: 14,
      foreground: "red",
      background: "white",
      trainer: "Pedro Caixinha",
    },
    {
      name: "Juventude",
      fullname: "Esporte Clube Juventude",
      base: 14,
      foreground: "white",
      background: "green",
      border: "white",
      trainer: "Jair Ventura",
    },
    {
      name: "Criciúma",
      fullname: "Criciúma Esporte Clube",
      base: 14,
      foreground: "black",
      background: "yellow",
      trainer: "Claudio Tencati",
    },
    {
      name: "Vitória",
      fullname: "Esporte Clube Vitória",
      base: 13,
      foreground: "red",
      background: "black",
      trainer: "Thiago Carpini",
    },
    {
      name: "Cuiabá",
      fullname: "Cuiabá Esporte Clube",
      base: 13,
      foreground: "yellow",
      background: "green",
      border: "yellow",
      trainer: "Bernardo Franco",
    },
    {
      name: "Atlético-GO",
      fullname: "Clube Atlético Goianiense",
      base: 13,
      foreground: "red",
      background: "black",
      trainer: "Vagner Mancini",
    },
    {
      name: "Santos",
      fullname: "Santos Futebol Clube",
      base: 13,
      foreground: "black",
      background: "white",
      trainer: "Fábio Carille",
    },
    {
      name: "Novorizontino",
      fullname: "Grêmio Novorizontino",
      base: 12,
      foreground: "black",
      background: "yellow",
      trainer: "Eduardo Baptista",
    },
    {
      name: "Sport",
      fullname: "Sport Club do Recife",
      base: 12,
      foreground: "black",
      background: "red",
      trainer: "Pepa",
    },
    {
      name: "América-MG",
      fullname: "América Futebol Clube Mineiro",
      base: 12,
      foreground: "green",
      background: "black",
      trainer: "Lisca",
    },
    {
      name: "Coritiba",
      fullname: "Coritiba Foot Ball Club",
      base: 12,
      foreground: "white",
      background: "green",
      border: "white",
      trainer: "Jorginho",
    },
    {
      name: "Ceará",
      fullname: "Ceará Sport Club",
      base: 12,
      foreground: "white",
      background: "black",
      trainer: "Leo Condé",
    },
    {
      name: "Goiás",
      fullname: "Goiás Esporte Clube",
      base: 12,
      foreground: "white",
      background: "green",
      border: "white",
      trainer: "Vagner Mancini",
    },
    {
      name: "Avaí",
      fullname: "Avaí Futebol Clube",
      base: 11,
      foreground: "darkblue",
      background: "white",
      trainer: "Enderson Moreira",
    },
    {
      name: "Vila Nova",
      fullname: "Vila Nova Futebol Clube",
      base: 11,
      foreground: "white",
      background: "red",
      trainer: "Luizinho Lopes",
    },
    {
      name: "Mirassol",
      fullname: "Mirassol Futebol Clube",
      base: 11,
      foreground: "green",
      background: "yellow",
      trainer: "Mozart",
    },
    {
      name: "Operário-PR",
      fullname: "Operário Ferroviário Esporte Clube",
      base: 10,
      foreground: "black",
      background: "white",
      trainer: "Rafael Guanaes",
    },
    {
      name: "Botafogo-SP",
      fullname: "Botafogo Futebol Clube",
      base: 10,
      foreground: "red",
      background: "white",
      trainer: "Zanardi",
    },
    {
      name: "Ituano",
      fullname: "Ituano Futebol Clube",
      base: 10,
      foreground: "red",
      background: "black",
      trainer: "Alberto Valentim",
    },
    {
      name: "Náutico",
      fullname: "Clube Náutico Capibaribe",
      base: 10,
      foreground: "red",
      background: "white",
      trainer: "Marquinhos Santos",
    },
    {
      name: "CRB",
      fullname: "Clube de Regatas Brasil",
      base: 10,
      foreground: "white",
      background: "red",
      trainer: "Hélio dos Anjos",
    },
    {
      name: "Guarani",
      fullname: "Guarani Futebol Clube",
      base: 10,
      foreground: "white",
      background: "green",
      border: "white",
      trainer: "Allan Aal",
    },
    {
      name: "Ponte Preta",
      fullname: "Associação Atlética Ponte Preta",
      base: 10,
      foreground: "black",
      background: "white",
      trainer: "Nelsinho Baptista",
    },
    {
      name: "Chapecoense",
      fullname: "Associação Chapecoense de Futebol",
      base: 10,
      foreground: "white",
      background: "green",
      border: "white",
      trainer: "Gilmar dal Pozzo",
    },
  ];
}
