import type { Color } from "../types";

export type TeamSeed = {
  name: string;
  fullname?: string; // make this mandatory later
  base: number;
  foreground: Color;
  background: Color;
  border?: Color | "transparent";
  trainer: string;
};

export function brazilianTeams(): TeamSeed[] {
  return [
    {
      name: "Botafogo",
      base: 18,
      foreground: "white",
      background: "black",
      trainer: "Artur Jorge",
    },
    {
      name: "Palmeiras",
      base: 18,
      foreground: "white",
      background: "green",
      border: "white",
      trainer: "Abel Ferreira",
    },
    { name: "Flamengo", base: 18, foreground: "black", background: "red", trainer: "Filipe Luís" },
    {
      name: "Atlético-MG",
      base: 17,
      foreground: "white",
      background: "black",
      trainer: "Gabriel Milito",
    },
    { name: "São Paulo", base: 16, foreground: "red", background: "white", trainer: "Zubeldia" },
    { name: "Fortaleza", base: 16, foreground: "blue", background: "red", trainer: "Vojvoda" },
    {
      name: "Internacional",
      base: 16,
      foreground: "white",
      background: "red",
      trainer: "Roger Machado",
    },
    {
      name: "Grêmio",
      base: 16,
      foreground: "white",
      background: "darkblue",
      trainer: "Renato Gaúcho",
    },
    {
      name: "Corinthians",
      base: 16,
      foreground: "black",
      background: "white",
      trainer: "Ramón Díaz",
    },
    {
      name: "Fluminense",
      base: 15,
      foreground: "red",
      background: "green",
      border: "red",
      trainer: "Mano Menezes",
    },
    {
      name: "Cruzeiro",
      base: 15,
      foreground: "white",
      background: "darkblue",
      trainer: "Fernando Diniz",
    },
    {
      name: "Athlético",
      base: 15,
      foreground: "red",
      background: "black",
      trainer: "Lucho González",
    },
    { name: "Bahia", base: 15, foreground: "red", background: "darkblue", trainer: "Rogério Ceni" },
    { name: "Vasco", base: 15, foreground: "black", background: "white", trainer: "Rafael Paiva" },
    {
      name: "Bragantino",
      base: 14,
      foreground: "red",
      background: "white",
      trainer: "Pedro Caixinha",
    },
    {
      name: "Juventude",
      base: 14,
      foreground: "white",
      background: "green",
      border: "white",
      trainer: "Jair Ventura",
    },
    {
      name: "Criciúma",
      base: 14,
      foreground: "black",
      background: "yellow",
      trainer: "Claudio Tencati",
    },
    {
      name: "Vitória",
      base: 13,
      foreground: "red",
      background: "black",
      trainer: "Thiago Carpini",
    },
    {
      name: "Cuiabá",
      base: 13,
      foreground: "yellow",
      background: "green",
      border: "yellow",
      trainer: "Bernardo Franco",
    },
    {
      name: "Atlético-GO",
      base: 13,
      foreground: "red",
      background: "black",
      trainer: "Vagner Mancini",
    },
    {
      name: "Santos",
      base: 13,
      foreground: "black",
      background: "white",
      trainer: "Fábio Carille",
    },
    {
      name: "Novorizontino",
      base: 12,
      foreground: "black",
      background: "yellow",
      trainer: "Eduardo Baptista",
    },
    { name: "Sport", base: 12, foreground: "black", background: "red", trainer: "Pepa" },
    { name: "América-MG", base: 12, foreground: "green", background: "black", trainer: "Lisca" },
    {
      name: "Coritiba",
      base: 12,
      foreground: "white",
      background: "green",
      border: "white",
      trainer: "Jorginho",
    },
    { name: "Ceará", base: 12, foreground: "white", background: "black", trainer: "Leo Condé" },
    {
      name: "Goiás",
      base: 12,
      foreground: "white",
      background: "green",
      border: "white",
      trainer: "Vagner Mancini",
    },
    {
      name: "Avaí",
      base: 11,
      foreground: "darkblue",
      background: "white",
      trainer: "Enderson Moreira",
    },
    {
      name: "Vila Nova",
      base: 11,
      foreground: "white",
      background: "red",
      trainer: "Luizinho Lopes",
    },
    { name: "Mirassol", base: 11, foreground: "green", background: "yellow", trainer: "Mozart" },
    {
      name: "Operário-PR",
      base: 10,
      foreground: "black",
      background: "white",
      trainer: "Rafael Guanaes",
    },
    { name: "Botafogo-SP", base: 10, foreground: "red", background: "white", trainer: "Zanardi" },
    {
      name: "Ituano",
      base: 10,
      foreground: "red",
      background: "black",
      trainer: "Alberto Valentim",
    },
    {
      name: "Náutico",
      base: 10,
      foreground: "red",
      background: "white",
      trainer: "Marquinhos Santos",
    },
    { name: "CRB", base: 10, foreground: "white", background: "red", trainer: "Hélio dos Anjos" },
    {
      name: "Guarani",
      base: 10,
      foreground: "white",
      background: "green",
      border: "white",
      trainer: "Allan Aal",
    },
    {
      name: "Ponte Preta",
      base: 10,
      foreground: "black",
      background: "white",
      trainer: "Nelsinho Baptista",
    },
    {
      name: "Chapecoense",
      base: 10,
      foreground: "white",
      background: "green",
      border: "white",
      trainer: "Gilmar dal Pozzo",
    },
  ];
}
